### ISSUE TITLE
Incorrect documentation URL

### ISSUE THREAD

**Issue by rth** [iodide-project/docs#9]
The https://iodide.io/docs/ URL indicated in this repo is incorrect and return 404 status code.

https://iodide.io/ works (and is very nice), but as far as I can tell there is no obvious links to it from https://github.com/iodide-project/iodide README (maybe I missed something), so users might have a difficult time finding it.

**Comment by wlach** [comment]
We changed the deployment strategy for the docs a while ago, docs are now in the main iodide repository under docs/
